# Generated by Django 5.0.1 on 2024-01-27 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateTimeField(db_index=True, verbose_name='Rent At DateTime')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rent Price')),
                ('due_date', models.DateField(verbose_name='Expected Return Date')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Return At DateTime')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_logs', to='book_manager.book')),
                ('rent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
