# Generated by Django 5.0.1 on 2024-01-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(verbose_name="First name")),
                ("last_name", models.CharField(verbose_name="Last name")),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Birthdate"),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profile",
            },
        ),
    ]
