# Generated by Django 5.0.1 on 2024-01-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ISBN: The International Standard Book Number')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('total_in_store', models.PositiveSmallIntegerField(default=0, verbose_name='Total In Store')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('authors', models.ManyToManyField(related_name='books', to='book_manager.author')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('title',),
            },
        ),
    ]
