# Generated by Django 5.0.1 on 2024-02-06 13:40

import book_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=book_manager.models.Book._image_path),
        ),
    ]
